### ISSUE TITLE
Wrong Player Awarded

### ISSUE THREAD

**Issue by fentoozlerx** [Handyfon/Farchievements#21]
When I award a player with an achievement, it awards the player one position above the intended player.

**Comment by Tyeia** [comment]
I am additionally having this issue. Mine appears to be related to changing the name of players, as it worked fine until i renamed the player's logins

**Comment by Tyeia** [comment]
I managed to resolve this issue by going into settings.db and deleting the clientsync data and reawarding the achievements

**Comment by viniciusaraujo093** [comment]
@Tyeia I tried to do the same steps and not work, u know another way to get this module give the achievements to right player? 
I deleted the settings.db from my world but the file come back and nothing changes.

**Comment by Tyeia** [comment]
@viniciusaraujo093 I actually opened the settings.db file and found the piece of data for each player and manually deleted it. I'm not sure why fully deleting the settings file did not work for you.

**Comment by xathick** [comment]
The problem is how the achivements are registed. The order of the players tab and the ones in the settings.db file are diferent. Take a screenshot of the ones in the tab, and put them in the same order in the settings.db file. While doing this, make sure foundry is closed and you only have one clientsync  in the file. That should work.
